### PR TITLE
Add a SKIPPED result status for stages

### PR DESCRIPTION
**Pull request by FlorianVeaux**
A bit tricky what's going on here.
First Jenkins on its own does not differentiate in the UI a failed stage in a pipeline from a stage that has been skipped because of an earlier failure.
For example in this job, only the first stage failed but all the others are marked as failed: image

While that's how jobs status are stored by Jenkins, BlueOcean is able to mark those other jobs as "skipped", see:
image

Currently skipped jobs are marked as failed in Datadog, this PR introduces a new tag value "result:SKIPPED" for those jobs

### CODE REVIEW

**Comment by FlorianVeaux** [comment]
Fix for https://github.com/jenkinsci/datadog-plugin/issues/146

**Review by mgarabed — APPROVED** [review]
Nice improvement!

**Comment by patelronak** [comment]
This is great.  Thanks.

**Comment by FlorianVeaux** [comment]
Test failure is a windows flake on the jenkins-owned CI. Confirmed working as expected in a lab.

**Pull request merged**
