### PR TITLE
Fix missing logs attached to the APM trace

### PR DESCRIPTION
**Pull request by drodriguezhdez**
### Requirements for Contributing to this repository

* Fill out the template below. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* The pull request must only fix one issue at the time.
* The pull request must update the test suite to demonstrate the changed functionality.
* After you create the pull request, all status checks must be pass before a maintainer reviews your contribution. For more details, please see [CONTRIBUTING](/CONTRIBUTING.md). 

### What does this PR do?

* Fix missing logs attached to the APM trace

### Description of the Change

The `client.startBuildTrace` and `client.finishBuildTrace` methods invocation have been moved to the RunListener methods `onInitialize` and `onFinalized` instead of `onStarted` and `onCompleted` to avoid missing some log traces generated during those phases.

### Review checklist (to be filled by reviewers)

- [ ] Feature or bug fix MUST have appropriate tests (unit, integration, etc...)
- [ ] PR title must be written as a CHANGELOG entry [(see why)](/CONTRIBUTING.md#pull-request-title)
- [ ] Files changes must correspond to the primary purpose of the PR as described in the title (small unrelated changes should have their own PR)
- [ ] PR must have one `changelog/` label attached. If applicable it should have the `backward-incompatible` label attached.
- [ ] PR should not have `do-not-merge/` label attached.
- [ ] If Applicable, issue must have `kind/` and `severity/` labels attached at least.

### CODE REVIEW

**Review by FlorianVeaux — COMMENTED** [review]
Let's add tests for this. But looks good

**Comment by drodriguezhdez** [comment]
This change is already covered by the `DatadogBuildListenerIT` test. Nothing to add additionally.

**Comment by FlorianVeaux** [comment]
I mean tests for the new feature that is being added here. We should check that logs submitted before `onStarted` are now fetched.

**Comment by drodriguezhdez** [comment]
Added 👍

**Review by FlorianVeaux — APPROVED** [review]

**Pull request merged**
